### PR TITLE
FND-276 #comment - GitHub issue #97

### PR DESCRIPTION
**Pull request by ElisaKendall**
## Description

Revise the definition of organization as suggested, to replace 'person' with 'individual' and eliminate unnecessary / unused legitimate organizations ontology to simplify the hierarchy

Fixes: #97, JIRA issue BE-276

## Checklist:

- [x] I'm familiar with the [FIBO developer quide](../CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [x] My contribution follows the [principles of best practices for FIBO](../ONTOLOGY_GUIDE.md).

### CODE REVIEW

**Comment by ElisaKendall** [comment]
How would you like it to read?  The only thing I changed in the definition itself was to change "person or persons" to individual or individuals.  The rest was there before.

**Comment by ElisaKendall** [comment]
I would rather quote a standard definition for organization than invent yet another one.

**Comment by trypuz** [comment]
@ElisaKendall; [The sign-off is missing.](https://github.com/edmcouncil/fibo/pull/830/checks?check_run_id=401645540)

**Comment by rivettp** [comment]
The definition I already quoted from the W3C standard, which we claim to be aligned with, is more general and more appropriate for FIBO than the narrow, authority-based one used by ISO for one specific standard.

**Comment by ElisaKendall** [comment]
The W3C definition is circular whereas the ISO definition is not.  I could remove "of authority" but I much prefer referencing an ISO definition that meets ISO 704 requirements, which we have said that we are doing.  Mike objected to limiting organizations to people - so I'm not sure what we are talking about in any case. All of the uses of organization that I know of in FIBO are of groups of one or more people.  I don't believe we have said that we would cover organizing artificial agents with our definition of organization, thus I propose the following:

unique framework within which a person or persons act, or are designated to act, towards some purpose

At least is is not circular, and eliminates the issue with "of authority", which I disagree is a problem, since all of our organizations are academic, research institutes, companies, or government entities.

**Comment by rivettp** [comment]
Defining Organization as a "unique framework" seems pretty arcane to any business person. And "framework" itself is used in all sorts of different ways. 
Note that the examples of organizations you listed would be FormalOrganizations in FIBO: the generic Organization is intended to encompass social clubs etc as clearly stated, even though we might not need them for FIBO per se.
If you think "organized" is too circular in the W3 definition (I don't) then how about "grouped"?

**Comment by trypuz** [comment]
> @ElisaKendall; [The sign-off is missing.](https://github.com/edmcouncil/fibo/pull/830/checks?check_run_id=401645540)

DCO is OK now.

**Pull request merged**
