### PR TITLE
GitHub-1956 - Incorrect definition of EBITDA

### PR DESCRIPTION
**Pull request by ElisaKendall**
## Description

Modified the definition of EBITDA to better reflect its common interpretation per SME

Fixes: #1956 

## Checklist:

- [x] I'm familiar with the [FIBO developer quide](https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [x] My contribution follows the [principles of best practices for FIBO](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md).
- [x] My changes have been reconciled with latest master and no merge conflicts remain.
- [x] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [x] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [x] The issue has been tested locally using a reasoner (for ontology changes).

### CODE REVIEW

**Review by rivettp — CHANGES_REQUESTED** [review]
I think "measure of cash flow" is a bit vague. I suggest (helped by ChatGPT)  "a financial metric that calculates a company's operational profitability by excluding non-operating expenses and non-cash charges."

**Comment by ElisaKendall** [comment]
> I think "measure of cash flow" is a bit vague. I suggest (helped by ChatGPT) "a financial metric that calculates a company's operational profitability by excluding non-operating expenses and non-cash charges."

The generally accepted accounting definition (GAAP does not have one, but I have an SME who knows), is that it is either a measure or estimate of cash flow, NOT a financial metric. And it is not always calculated the same way, and it is not considered usable for some reporting, such as to various government entities because it can be manipulated. The definition I've used is adapted from Barrons and Bruce's input.

**Comment by jfgemski** [comment]
Agreed

 

John

 

***@***.*** ***@***.***>  | O: (516) 826-0701| M: (516) 353-0004

**Review by jfgemski — DISMISSED** [review]

**Review by tahoeblue — DISMISSED** [review]

**Comment by rivettp** [comment]
I'm not fixated on measure vs metric, but I do think it's important to talk about a measure of profit as opposed to cashflow. You can earn a profit based on receivables (included in EBIDTA) but that does not mean you have the cash coming in!

"Cash flow, on the other hand, is a measure of the actual cash coming in and going out of the business. It reflects the company's ability to generate cash, which is crucial for meeting its short-term obligations and funding its operations. Unlike EBITDA, cash flow accounts for the actual timing of when revenues are received and expenses are paid. It includes changes in working capital and therefore is a direct indicator of a company's liquidity.

In essence, while EBITDA provides a view of a company's operational profitability by removing certain accounting and financial factors, cash flow directly measures the company's ability to generate and use cash. They serve different, but complementary, purposes in financial analysis."

**Review by jfgemski — APPROVED** [review]

**Review by rivettp — APPROVED** [review]

**Pull request merged**
