### PR TITLE
GitHub-2039 - Implicit punning of OWL Classes in triples (as objects) with object property

### PR DESCRIPTION
**Pull request by ElisaKendall**
## Description

Revised the modeling strategy for ISO 15022/20022 corporate actions and example market indices baskets to eliminate punning issues

Fixes: #2039 

## Checklist:

- [x] I'm familiar with the [FIBO developer quide](https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [x] My contribution follows the [principles of best practices for FIBO](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md).
- [x] My changes have been reconciled with latest master and no merge conflicts remain.
- [x] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [x] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [x] The issue has been tested locally using a reasoner (for ontology changes).

### CODE REVIEW

**Review by jfgemski — DISMISSED** [review]

**Review by tahoeblue — DISMISSED** [review]

**Review by rivettp — CHANGES_REQUESTED** [review]
It is quite an unintuitive modeling approach to have restrictions on Individuals, and I would need to understand the rationale. 
Worse, it seems to have a flaw - use of someValuesFrom requires at least one instance to be classified by any classifier.

**Comment by ElisaKendall** [comment]
@rivettp It is perfectly legal to do this, and we used this pattern quite successfully at Wells Fargo and on other projects such as IDMP. It is needed when an individual classifies something when it applies to all members of that class. We originally applied this approach for the CFI classification scheme, but agreed to change that given that every organization uses the CFI classification and it is now mandated by the FDTA. Many organizations do not use ISO 15022 to classify corporate actions, however, and we would be mandating its use in all cases if we follow the pattern used for the CFI. If people are using this ontology then they are committing to classifying corporate actions using the ISO 15022 classification scheme, and so the at least one corporate action classified by that scheme is entirely appropriate.

**Comment by ElisaKendall** [comment]
@rivettp What we had previously caused punning, so either we do this, or we add restrictions on the elements of the two ontologies that represent the corporate actions in this local ontology. That's less intuitive IMHO.

**Comment by rivettp** [comment]
You didn't address my second comment that it requires at least one instance of any action.

**Comment by ElisaKendall** [comment]
@rivettp It does, but using an open world assumption one would say that there is an instance of such an action somewhere in the universe but we may not know about it. Also perfectly legal. It would only be required if you close the world.

**Comment by ElisaKendall** [comment]
@rivettp The other option would be to change it to either all values from or min 0. I can make that change, but all values from might be problematic for people wanting to use the ACTUS classifiers.

**Comment by ElisaKendall** [comment]
@rivettp I would have to try it with examples, using two classifiers in different schemes for the same thing, such as a repurchase offer, then run the reasoner to see what happens. It might make a logical equivalence between the two, but that might be ok if they are truly equivalent. With some values from, that leaves the door open for some actions to not be classified by a particular code.

**Comment by rivettp** [comment]
The restriction would apply only to an individual code such as BONU and declares it's a member of the class of things that classify only instances of BonusIssue. 
I think. 
The fact that it's hard to think through, and even you feel the need to discover what happens in a reasoner, is a bit of a warning sign that we need to tread carefully with this pattern. I think something that's simple and obvious may be more important than an extra level of checking. Especially since there are many checks we forget about even trying due to reasoner performance, even for toy examples let alone enterprise data. Not to mention for DL safe reasons.
And we shouldn't forget about the possibility of expressing constraints using SHACL - which is what it's designed for.

**Review by rivettp — APPROVED** [review]
Happier with the allValuesFrom

**Review by jfgemski — APPROVED** [review]

**Pull request merged**
