### PR TITLE
Fbc 265

### PR DESCRIPTION
**Pull request by dallemang**
## Description

This pull request has no content change in comparison to Pete's pull request https://github.com/edmcouncil/fibo/pull/1218

I have simply run it through the serializer, so that the diffs against the current master are easier to read. 

I want to suggest that we merge this PR instead of 1218, so that the git history is easier to follow. 

Fixes: #ISSUE_NUMBER

## Checklist:

- [ X] I'm familiar with the [FIBO developer quide](../CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [ X] My contribution follows the [principles of best practices for FIBO](../ONTOLOGY_GUIDE.md).
- [X ] My changes have been reconciled with latest master and no merge conflicts remain.
- [ X] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [ X] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [ X] The issue has been tested locally using a reasoner (for ontology changes).

### CODE REVIEW

**Comment by dallemang** [comment]
I want to tag @rivettp  to bring this to his attention; the diff on the github page for this PR is a lot easier to evaluate than on 1218.  I'd like you to confirm that the content change is what you intended, and approve this one instead of 1218.  This will make the git history easier to read. 

We'll need a second approval; perhaps @trypuz  can do that? 
@ElisaKendall  has already approved the original.

**Comment by rivettp** [comment]
I did run serializer on the original, but had to copy it to my Windows machine to do it, due to the serializer catastrophically failing on Ubuntu (see comment on #1217, apparently @ElisaKendall knows of a workround in the precommit file). Though, after copying it back, the diffs appeared fine in VS Code on my Ubuntu machine from which I did the commit and PR, something went weird with line ends in the GitHub diff.

**Review by rivettp — APPROVED** [review]

**Review by ElisaKendall — APPROVED** [review]

**Comment by trypuz** [comment]
@dallemang, @rivettp - I wouldn't say I like the way this PR has been handled. ISSUE_NUMBER is missing, no signature (and DCO), no milestone, no labels, no linked issues. I hope we won't have anything like this in the future.

**Comment by rivettp** [comment]
@trypuz those things were on the original PR I raised, #1218.

**Pull request merged**
