### PR TITLE
FND-346  - Need the definition of a structured name and definition of a new datatype for the combination of xsd:string and rdf:langString

### PR DESCRIPTION
**Pull request by ElisaKendall**
Signed-off-by: Elisa Kendall <ekendall@thematix.com>

## Description

This resolution introduces a new custom datatype, Text, which represents the union of xsd:string and rdf:langString, allowing better representation of names and descriptions that may be expressed in various languages.  It also adds the concept of a structured name, and augments parties, people, and organizations to use it, as a current approach to handling name patterns rather than less expressive string values, as appropriate.

Fixes: #1533 / FND-346 / FND-245 / FND-74

## Checklist:

- [x] I'm familiar with the [FIBO developer quide](https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [x] My contribution follows the [principles of best practices for FIBO](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md).
- [x] My changes have been reconciled with latest master and no merge conflicts remain.
- [x] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [x] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [x] The issue has been tested locally using a reasoner (for ontology changes).

### CODE REVIEW

**Comment by trypuz** [comment]
@mereolog, this PR is still WIP. Should I review it as it is?

**Review by dsnewman — APPROVED** [review]

**Review by dallemang — APPROVED** [review]
This  clearly makes a lot of sense from a modeling point of view - can you make a comment about performance, I suppose mostly in terms of Pellet evaluation of the model?  Does this make a significant change in that process?

**Comment by ElisaKendall** [comment]
@dallemang - Based on the testing I've done so far, the change has had negligible impact on performance, if any, with respect to running Pellet.  Having said this, we don't have any examples of people in our set of examples in release for FIBO, so I'm not surprised about the lack of impact.  Now that this initial change is in, though, there may be some downstream updates related to organizational names that should be done, such as those that we have added in FBC for trading or operational name, as well as the need to add DBA for sole proprietorships. My intent was to put those changes off until this initial pull request was complete, and then make those changes, and see what happens.  My guess is that for the few examples that might be impacted, it will still be minimal with respect to FIBO itself.  For operational environments, there may need to be some programmatic changes to create the various name individuals associated with an organization that might add overhead in the materialization process.  Reasoning / SPARQL performance hits should be minimal though. And, I'll make sure that the existing properties can be used with or without the change to allow for their use with either a reified structural name or not.  I've already made the change to allow most of them to use the Text datatype, but the union includes xsd:string so any names in individuals that use xsd:string should still work as well.

**Comment by rivettp** [comment]
This is a major architectural change and should be fully discussed rather than being pushed through over a weekend.
That's not even mentioning the significant practical and cultural problems I can foresee with the approach to naming.
Finally, putting the new datatype Text into the Agents ontology, when it is intended for widespread use, is architecturally harmful. It's already resulted in a proposed change to Markets ontology requiring a new and logically unnecessary dependency on Agents.

**Comment by ElisaKendall** [comment]
This is not 'new' - you yourself reviewed this pattern in the slides that Dean and I presented at Enterprise Data World.  The revision is simply codifying that pattern for use in FIBO.  It is not mandated, however - the properties that we've specified to use the text datatype do not have a domain, and the union allows for backwards compatibility with the original use of these properties elsewhere in FIBO.

The concept of a Name as a class was added to agents because that's where it is needed for initial use, and the parties, people and organizations ontologies have already imported it and extended it in the past.  We recently simplified some of those relationships in parties, but if you look historically the relationship was there until earlier this year.  So this is nothing new.  The name class has only two elements as we discussed for a person - their full name and a surname that can be used for sorting, which is optional.  It does not include the various culturally possibly insensitive properties that remain in the ontology but are not used.  It adds an optional prefix and suffix which were a gap raised in another FND issue, however.  

There were 3 options for creation of the Text datatype: (1) put it in Agents where it is first used and needed, (2)_ put it in annotation vocabulary that everything uses, or (3) create a new tiny ontology, which you have objected to on many occasions for that purpose.  I may not have done this the way you would have, but it was a pragmatic solution based on the first place where it is used.

**Pull request merged**
