### PR TITLE
etc folder cleanup

### PR DESCRIPTION
**Pull request by mereolog**
Signed-off-by: mereolog <pawel.garbacz@makolab.com>

## Description

This PR removes old, obsolete subfolders from [etc folder](https://github.com/edmcouncil/fibo/tree/master/etc).

Fixes: #1734

## Checklist:

- [X] I'm familiar with the [FIBO developer quide](https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [X] My contribution follows the [principles of best practices for FIBO](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md).
- [X] My changes have been reconciled with latest master and no merge conflicts remain.
- [X] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [X] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [X] The issue has been tested locally using a reasoner (for ontology changes).

### CODE REVIEW

**Review by przemekgradzki — CHANGES_REQUESTED** [review]
Due to the deletion of directiries/files, the following references to them should be removed:
https://github.com/edmcouncil/fibo/blob/9bd53f900a8d99fc0ef9efcdc6cccad432b75fac/CONTRIBUTING.md?plain=1#L255-L256
https://github.com/edmcouncil/fibo/blob/9bd53f900a8d99fc0ef9efcdc6cccad432b75fac/etc/README.md?plain=1#L11-L14
https://github.com/edmcouncil/fibo/blob/9bd53f900a8d99fc0ef9efcdc6cccad432b75fac/etc/README.md?plain=1#L18-L22

**Review by rivettp — CHANGES_REQUESTED** [review]
I think there is some useful content here that I don't think is elsewhere. Particularly under the "site" directory there are several documents such as FIBOMatadataSpecification, various decisions and policies and FAQs and the FIBO Primer. Though they have been (arbitrarily IMO) excluded from the current FIBO site, they are still useful content.

**Comment by mereolog** [comment]
> I think there is some useful content here that I don't think is elsewhere. Particularly under the "site" directory there are several documents such as FIBOMatadataSpecification, various decisions and policies and FAQs and the FIBO Primer. Though they have been (arbitrarily IMO) excluded from the current FIBO site, they are still useful content.

These were useful when they were created and updated, but most of the specifications and documents there are outdated. For instance, the latest version of FIBOMatadataSpecification requires properties that are long gone (i.e. unused), e.g., sm:specificationTitle. FIBO Primer contains a great deal of content about SMIF UML Diagrams, which we do not produce any more. Etc. 
Also some of this content found their way to the [Ontology Guide](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md) or [How to Contribute](url) spec or at least can be found there. So I think the spec to be found in etc folder are obsolete and might be misleading or confusing. Also having the same principles in multiple places would increase the cost of maintenance. In the end of the day we would end up in the well known traps one falls into when such principles like "single source of truth" are ignored.

I would be happy to update some of these specs and bring the updates back to the repository if time allows. Any other contributor to FIBO is welcome to join me in this effort as well.

**Review by przemekgradzki — APPROVED** [review]
https://github.com/edmcouncil/fibo/blob/a23818a6ba1029e5dad9905c604349e51484990b/CONTRIBUTING.md?plain=1#L251-L257

should be updated

**Pull request merged**
