### PR TITLE
datadictionary and fibopedia removed from the Jenkins pipeline

### PR DESCRIPTION
**Pull request by trypuz**
Signed-off-by: Robert Trypuz <robert.trypuz@makolab.com>

## Description

FIBOPedia is deprecated. Data dictionary is now served in one file (Excel or CSV).

Fixes: https://github.com/edmcouncil/ontology-publisher/issues/13

## Checklist:

- [X] I'm familiar with the [FIBO developer quide](../CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [X] My contribution follows the [principles of best practices for FIBO](../ONTOLOGY_GUIDE.md).

### CODE REVIEW

**Comment by dallemang** [comment]
I agree with Pete about those other products; indeed, we don't need the whole thing, but I would like to at least see an issue raised to resurrect the particular products that are not served by the current configuration.

**Comment by trypuz** [comment]
@rivettp, @dallemang, it seems that you misunderstood what this PR is about. We do not serve the two FIBO products in question on our website, so it makes no sense to build them every time we change anything in this repo. So, we do not discuss here whether we need the (old) datadictionary and fibopedia. It is a separate issue that can be discussed elsewhere. BTW, I will be happy to welcome new FIBO products, providing there will be a community group committing itself to its dev and maintenance.

**Comment by trypuz** [comment]
@rivettp, you requested changes yesterday. But they cannot be addressed, because they do not exactly concern this PR. Let's continue the discussion about the FIBO products here: #857 and #858.

**Comment by rivettp** [comment]
@trypuz my proposal is to Close this PR and not merge it, as @dallemang also suggests. It's pointless to remove these products and then reinstate them as part of those other issues. If we decide to reject those other issues then I guess we can re-open this PR.

**Comment by trypuz** [comment]
@rivettp, because we have FIBO Viewer some of the FIBO products have to be rethought. fibopeadia and datadictionary (I'm using the names of the products from the Jenkinsfile), cannot go to production as they are. In #857 and #858 we discuss the features of fibopeadia and datadictionary that are missing in the FIBO products we are offering on our website.

**Comment by rivettp** [comment]
As explained on Slack, this has killed the production of modules-clean.rdf (the basis of the FIBOpedia files) which our loader relies on.

**Comment by trypuz** [comment]
We have an issue for this: #857.

**Comment by rivettp** [comment]
Issue #857 is for a new published/visible product. I'm talking about the production of the invisible file modules-clean.rdf which has been used (downloaded) by our software at least. Given that the FIBOpedia files were not visibly published on the new site anyway, and did not take much resource, I don't see the harm in restoring the generation of the files pending the resolution of #857.

**Comment by bobbinteegarden** [comment]
I agree with Pete.  We seem to be hiding (or discontinuing) what in the past was useful to a user of FIBO.  Why?
 
Bobbin Teegarden
CTO/Chief Architect, OntoAge
 <mailto:bobbin@ontoage.com> bobbin@ontoage.com
206.979.0196 cell
425.378.0131 home/fax
Bellevue, WA

**Pull request merged**
