### PR TITLE
Extending hygiene tests set - no unused imports

### PR DESCRIPTION
**Pull request by mereolog**
Signed-off-by: Pawel Garbacz <pawel.garbacz@makolab.com>

## Description

This test is to find unused imports in the whole (aggregated) FIBO ontology.

Fixes: #1081

## Checklist:

- [X] I'm familiar with the [FIBO developer quide](../CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [X] My contribution follows the [principles of best practices for FIBO](../ONTOLOGY_GUIDE.md).
- [X] My changes have been reconciled with latest master and no merge conflicts remain.
- [X] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [X] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [X] The issue has been tested locally using a reasoner (for ontology changes).

### CODE REVIEW

**Comment by mereolog** [comment]
@rivettp 
As for:
> Hmm I don't see where the triple ?s ?p ?o is linked to the ?importingOntology. Which would actually be hard to do unless you use the quad representation which has a named graph for each ontology.
> 
I can add the following clause to FILTER NOT EXISTS filter:
`FILTER (CONTAINS(str(?s), str(?importingOntology)) || CONTAINS(str(?p), str(?importingOntology)) || CONTAINS(str(?o), str(?importingOntology)))
`

**Comment by mereolog** [comment]
@rivettp 
As for:

> There could be some false matches here (which will be considered a usage whereas it's not) e.g. if one ontology has a URI which is equal to another with an extra word or two added.
> Also if a URI is contained in the string that is the object of a datatype or annotation property.

If I get you right, the following change may a remedy.
Instead of:
`FILTER (CONTAINS(CONCAT(str(?s), str(?p), str(?o)),str(?importedOntology))).`
we could have:
`FILTER (REGEX(str(?s), CONCAT(str(?importedOntology),".+")) || REGEX(str(?p), CONCAT(str(?importedOntology),".+")) || REGEX(str(?o), CONCAT(str(?importedOntology),".+")))`

**Comment by ElisaKendall** [comment]
One thing I am wondering about - there is at least one case where I've explicitly imported an ontology in the latest revisions to loans because that ontology adds restrictions on DebtInstrument that we need for a loan, but there are no direct references to anything.  Would this require that I add some reference to the SEC/Debt/DebtInstruments ontology in the importing ontology to keep that import statement?

**Comment by mereolog** [comment]
@ElisaKendall 
Which ontology did you mean?

**Pull request closed without merging**
